### ISSUE TITLE
feature/add-dark-theme-support-to-the-webapp

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [Manuel-Suarez-Abascal/travel-bruv#5]
# Ticket Description

Add dark theme support to our web app.

# Why?

Dark Theme benefits:

- Improved Readability of Text
- Better Contrast 
- Reduced Eye Fatigue 
- Less Flicker (if existing issues) 
- Less Blue Light 
- Less Prone to Triggering Photophobia

# Other information

We can take inspiration from the [Create React App Official Website's Dark Theme](https://create-react-app.dev/).

**Comment by caballerof09** [comment]
Good idea, adding a dark mode is great but it will be better if it could work by the time zone and activate only at night or by the user request.

**Comment by Manuel-Suarez-Abascal** [comment]
> Good idea, adding a dark mode is great but it will be better if it could work by the time zone and activate only at night or by the user request.

@caballerof09 great idea! 💡 I think it's totally feasible, I have been reading this blog as [inspiration](http://www.onlineaspect.com/2007/06/08/auto-detect-a-time-zone-with-javascript/.) I'll open a new issue since it was the ticket's scope! I'll close this issue now since [this PR](https://github.com/Manuel-Suarez-Abascal/travel-bruv/pull/6) solved it
